DROP DATABASE IF EXISTS ejercicio_pub;
CREATE DATABASE ejercicio_pub;
USE ejercicio_pub;

CREATE TABLE LOCALIDAD(
    COD_LOCALIDAD INT PRIMARY KEY,
    NOMBRE CHAR(50) NOT NULL
);

CREATE TABLE PUB(
    COD_PUB CHAR(10) PRIMARY KEY,
    NOMBRE CHAR(50) NOT NULL,
    LICENCIA_FISCAL CHAR(20) NOT NULL,
    DOMICILIO CHAR(100),
    FECHA_APERTURA DATE NOT NULL,
    HORARIO ENUM('HOR1', 'HOR2', 'HOR3') NOT NULL,
    COD_LOCALIDAD INT NOT NULL,
    FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD)
);

CREATE TABLE TITULAR (
    DNI_TITULAR CHAR(15) PRIMARY KEY,
    NOMBRE CHAR(50) NOT NULL,
    DOMICILIO CHAR(100),
    COD_PUB CHAR(10) NOT NULL,
    FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB)
);

CREATE TABLE EMPLEADO (
    DNI_EMPLEADO CHAR(15) PRIMARY KEY,
    NOMBRE CHAR(50) NOT NULL,
    DOMICILIO CHAR(100)
);

CREATE TABLE PUB_EMPLEADO (
    COD_PUB CHAR(10) NOT NULL,
    DNI_EMPLEADO CHAR(15) NOT NULL,
    FUNCION ENUM('CAMARERO', 'SEGURIDAD', 'LIMPIEZA') NOT NULL,
    PRIMARY KEY (COD_PUB, DNI_EMPLEADO),
    FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB),
    FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI_EMPLEADO)
);

CREATE TABLE EXISTENCIAS (
    COD_ARTICULO CHAR(10) PRIMARY KEY,
    NOMBRE CHAR(50) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL CHECK (PRECIO > 0),
    COD_PUB CHAR(10) NOT NULL,
    FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB)
);